### ISSUE TITLE
KeyError: 'Filename' in plot_all_results.py

### ISSUE THREAD

**Issue by StepanSaenko** [DessimozLab/OMArk#21]
Hello!

I was trying to generate some plots using plot_all_results.py. 
At first, I ran it this way: 
` /home/saenkos/OMArk/utils/plot_all_results.py -i ./` 
and everything was fine. 

But then I tried to use the ` -m` key with a file and got the error:

```
Traceback (most recent call last):
  File "/home/saenkos/OMArk/utils/plot_all_results.py", line 250, in <module>
    main_df, cont_df = integrate_external_data(main_df, cont_df, mapping_file, taxonomy_order=arg.taxonomy)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saenkos/OMArk/utils/plot_all_results.py", line 148, in integrate_external_data
    cont_df['Species name'] = [mapping.get(x,{}).get('Species name',x) for x in cont_df['Filename']]
                                                                                ~~~~~~~^^^^^^^^^^^^
  File "/home/saenkos/anaconda3/envs/myenv/lib/python3.11/site-packages/pandas-2.0.0rc1-py3.11-linux-x86_64.egg/pandas/core/frame.py", line 3745, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saenkos/anaconda3/envs/myenv/lib/python3.11/site-packages/pandas-2.0.0rc1-py3.11-linux-x86_64.egg/pandas/core/indexes/range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'Filename'
```

I checked the code, and here is my question:

Do the line 148 `cont_df['Species name'] = [mapping.get(x,{}).get('Species name',x) for x in cont_df['Filename']]`  and variable `cont_df ` take part in a plot generating? 

I mean, the plot-generating command has only `main_df ` variable: `plot_omark_df(main_df, savefile=output_figure)
`

When I commented it, the image was generated, but it was the same as before, with no differences using the `-m` key

Could you please provide examples of plots with provided mapping file and without?

Thank you.

**Comment by YanNevers** [comment]
Should  been fixed with release with commit 21f19b6 .
