### ISSUE TITLE
run standalone omark

### ISSUE THREAD

**Issue by bitezhu** [DessimozLab/OMArk#27]
Hi, I've installed omark on my local version. But it seems we need to keep network available to run omark. Is there any way to bypass the network requirements? 
Cheers,

**Comment by YanNevers** [comment]
Hello,

OMArk functionalities do not normally require any  network connection, provided you downloaded a local OMAmer database already. I am guessing the only time it would require internet access is upon first use, as it uses a local copy of the NCBI taxonomy database from ete3. If it is not present, ete3's NCBI module launch an automatic download.(See : http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html)
If you can obtain a copy of this database and copy it into ~/.etetoolkit/taxa.sqlite on your local server, I believe there will be no need for network anymore.

Please let me know if this is not possible or if this does not seem to be the problem. If the workaround is not possible, I will investigate what option I have to not make this a hard requirement.

Best,
Yannis

**Comment by bitezhu** [comment]
> Hello,
> 
> OMArk functionalities do not normally require any network connection, provided you downloaded a local OMAmer database already. I am guessing the only time it would require internet access is upon first use, as it uses a local copy of the NCBI taxonomy database from ete3. If it is not present, ete3's NCBI module launch an automatic download.(See : http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html) If you can obtain a copy of this database and copy it into ~/.etetoolkit/taxa.sqlite on your local server, I believe there will be no need for network anymore.
> 
> Please let me know if this is not possible or if this does not seem to be the problem. If the workaround is not possible, I will investigate what option I have to not make this a hard requirement.
> 
> Best, Yannis

Dear Yannis, thanks for your quick reply! It worked.
