### ISSUE TITLE
Database version mismatch

### ISSUE THREAD

**Issue by EricDeveaud** [DessimozLab/OMArk#37]
Hello, 

I just installed OMArk/0.3.0  from github repo head

when I run the `omamer` search with LUCA.h5 downloaded from https://omabrowser.org/All/LUCA.h5  given in doc.
I have the following warning  about database version mismatch

```
omamer search -t 64 --db /opt/gensoft/data/OMArk/0.3.0/LUCA.h5 --query ../../datas/OMArk/UP000005640_9606.fasta --out out.omamer
================================================================================

   _____ _____ _____
  |     |     |  _  |_____ ___ ___
  |  |  | | | |     |     | -_|  _|
  |_____|_|_|_|__|__|_|_|_|___|_|   v2.1.0

  OMAmer is licensed under the GNU Lesser General Public License 3.0 (LGPL-3.0).

================================================================================

Loading required libraries  [DONE]

================================================================================

Running OMAmer on build, using:
 - database: /opt/gensoft/data/OMArk/0.3.0/LUCA.h5
 - query: ../../datas/OMArk/UP000005640_9606.fasta
 - version: 2.1.0

================================================================================
WARNING: Database version mismatch: DB 2.0.3 / OMAmer 2.1.0

```

`omark` also claims there is database mismatch see:

```
omark -v -f out.omamer -d /opt/gensoft/data/OMArk/0.3.0/LUCA.h5 -o temp
INFO: Starting OMArk
WARNING: Database version mismatch: DB 2.0.3 / OMAmer 2.1.0
```

NB same pb with omamer embeded in OMArk (also v2.1.0) build from release [archive](https://github.com/DessimozLab/omamer/archive/refs/tags/v2.1.0.tar.gz)
regards

Eric

**Comment by alpae** [comment]
Dear @EricDeveaud 

thanks for reporting. We recently improved the OMAmer codebase to make p-value computation much more efficient. This gave rise to the new version of OMAmer 2.1.0. However, the database itself contains the same data in the same format than the 2.0 version, so you can simply ignore this warning.

Best wishes 
Adrian

**Comment by EricDeveaud** [comment]
OK thanks for the fast reply.

regards

Eric
