### ISSUE TITLE
Webserver job throws an error after 10 minutes

### ISSUE THREAD

**Issue by kkowalden** [DessimozLab/OMArk#8]
Hello,

Not sure if this is the appropriate place to post issues regarding the web version of the tool.

I've submitted my proteome of interest with the appropriate lineage, arthropod.

The webserver errors out after 10-15 minutes with:

`Error while running omamer
`
Are there any limitations, such as header formats, max number of sequences in the protein file, or incompatible characters in the fasta file?

Thanks,
Kim

**Comment by alpae** [comment]
Hi @kkowalden 

thanks to let us know. Indeed, we observe a few jobs that seem to be killed because they run out of memory. We will investigate on this and report back to you as soon as possible.

**Comment by alpae** [comment]
Hi @kkowalden 

I've implemented a fix for this issue that seems to work for me. could you please verify if your datasets also finish without errors.

**Comment by kkowalden** [comment]
I just tested the taxon that had failed previously, and now it finishes processing correctly!
Thank you for quickly resolving the issue!
