### ISSUE TITLE
Companion script for combined plot?

### ISSUE THREAD

**Issue by dirkjanvw** [DessimozLab/OMArk#9]
Hi, thanks for making this great tool available!
I was wondering whether it would be possible to include a companion script to produce a combined plot for a couple runs. In your [preprint](https://doi.org/10.1101/2022.11.25.517970), Figure 4, 5A and 5B have such a plot but I cannot discover a script to produce it on your GitHub. I was hoping to find something like the `generate_plot.py` script that BUSCO has. Would it be possible to include such a script here?

**Comment by YanNevers** [comment]
Thank for your nice comment and your interest!

I agree this is an important feature to visualize the data of multiple species. I need to do a slight reworking of the code I used on the manuscript. Once it is done, I will upload it (as soon as possible), likely as a companion script and as an interactive Jupyter Notebook.

**Comment by YanNevers** [comment]
Hi @dirkjanvw 

A companion script is now available on the utils folder of this repo (plot_all_results.py). It will generate plots similar to the one we present in the manuscript from a folder containing several OMArk output folders. It is also possible to interface with the data interactively using the associated Jupyter Notebook.

I plan to add more feature with time but I hope this version will be functional enough already. Let me know if you have any issue with it.

**Comment by dirkjanvw** [comment]
Hi @YanNevers 

Thanks a lot for providing this script! I really appreciate the effort :)

I have only found one small bug in it: I named my OMArk output folders after species names and I found out that sometimes this caused a mismatch between the first column of the mapping file and the actual name (_e.g._ helianthus_annuus became helianthus_ann). I fixed it in a fork I just created (as well as some small typos I discovered since I made the fork anyways). I will make a pull request in a couple minutes after commenting this, so you can see what I think would be the best fix.

**Comment by YanNevers** [comment]
Hi @dirkjanvw 

Thank you for reporting the bug, suggesting changes and even fixing typos! This is much appreciated! 
I agree your solution is a good fix so I just merged your fork into the main branch.

I am now closing the issue but feel free to reach out again if have other features requests.
